package modelo;
// Generated 13/06/2020 03:50:46 AM by Hibernate Tools 4.3.1



/**
 * Prestamo generated by hbm2java
 */
public class Prestamo  implements java.io.Serializable {


     private Integer id;
     private String codIsbn;
     private String codEjemp;
     private int cedula;

    public Prestamo() {
    }

    public Prestamo(String codIsbn, String codEjemp, int cedula) {
       this.codIsbn = codIsbn;
       this.codEjemp = codEjemp;
       this.cedula = cedula;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodIsbn() {
        return this.codIsbn;
    }
    
    public void setCodIsbn(String codIsbn) {
        this.codIsbn = codIsbn;
    }
    public String getCodEjemp() {
        return this.codEjemp;
    }
    
    public void setCodEjemp(String codEjemp) {
        this.codEjemp = codEjemp;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }




}


