package modelo;
// Generated 13/06/2020 03:50:46 AM by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int cedula;
     private String nombre;
     private String fechaNac;
     private String sexo;
     private String tipoUsu;
     private String estado;
     private int cantLibrosPrest;

    public Usuarios() {
    }

    public Usuarios(int cedula, String nombre, String fechaNac, String sexo, String tipoUsu, String estado, int cantLibrosPrest) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.fechaNac = fechaNac;
       this.sexo = sexo;
       this.tipoUsu = tipoUsu;
       this.estado = estado;
       this.cantLibrosPrest = cantLibrosPrest;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(String fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTipoUsu() {
        return this.tipoUsu;
    }
    
    public void setTipoUsu(String tipoUsu) {
        this.tipoUsu = tipoUsu;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getCantLibrosPrest() {
        return this.cantLibrosPrest;
    }
    
    public void setCantLibrosPrest(int cantLibrosPrest) {
        this.cantLibrosPrest = cantLibrosPrest;
    }




}


